name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .github/environment.yml
          init-shell: bash

      - name: Clone OpenMC
        run: |
          git clone https://github.com/openmc-dev/openmc --branch v0.15.0 $HOME/openmc

      - name: Install
        run: |
          python -m pip install .

      - name: Test examples
        run: |
          micromamba activate test-env
          OPENMC_EXAMPLES_DIR=$HOME/openmc/examples pytest -v ./test

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
